---
title: "Mini-Project 2"
author: "Your Name Here"
date: "March 24, 2017"
output: html_document
---


## Loading the data


```{r, include=FALSE}
library(tidyverse)
library(ggthemes)
library(maps)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
money_from_state <- contributions%>%
  group_by(state)%>%
  summarise(total_amt=sum(transaction_amt))%>%
  arrange(desc(total_amt))
```

```{r}
com_from_state <- committees%>%
  group_by(cmte_state)%>%
  summarise(total_com=n())%>%
  arrange(desc(total_com))%>%
  rename(state=cmte_state)

```

```{r}
cand_from_state <- candidates%>%
  group_by(cand_state)%>%
  summarise(total_cand=n())%>%
  arrange(desc(total_cand))%>%
  rename(state=cand_state)
```

```{r}
joined_state <- money_from_state%>%
  inner_join(com_from_state,by="state")

joined_state <- joined_state%>%
  inner_join(cand_from_state,by="state")
```

```{r}
all_states <- map_data("state")

```

```{r}
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )

```

```{r}
USA_base <- ggplot() + geom_polygon( data=all_states, aes(x=long, y=lat, group = group) )+
  ditch_the_axes
```

```{r}
ggplot(as.data.frame(money_from_state), aes(map_id = state)) +
    geom_map(aes(fill = total_amt), map = all_states)+
    expand_limits(x = all_states$long, y = all_states$lat)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
